/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_shift16_44 (
    input [15:0] a,
    input [3:0] b,
    input [5:0] alufn,
    output reg [15:0] shift
  );
  
  
  
  always @* begin
    shift = a;
    
    case (alufn[0+2-:3])
      3'h0: begin
        shift = a << b[0+3-:4];
      end
      3'h1: begin
        shift = a >> b[0+3-:4];
      end
      3'h3: begin
        shift = (a >> b[0+3-:4] | {5'h10{a[15+0-:1]}} << 5'h10 - b[0+3-:4]);
      end
      3'h4: begin
        shift = (a << b[0+3-:4] | a >> 5'h10 - b[0+3-:4]);
      end
      3'h5: begin
        shift = (a >> b[0+3-:4] | a << 5'h10 - b[0+3-:4]);
      end
    endcase
  end
endmodule
