/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] pinnumber,
    output reg [7:0] segpinnumberstage,
    output reg [7:0] segpinnumberones,
    output reg [7:0] segpinnumbertens,
    input button_start,
    input button_L,
    input button_R
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [25-1:0] M_cycle_pinnumber;
  reg [64-1:0] M_cycle_ledmatrix;
  cycle_2 cycle (
    .clk(clk),
    .rst(rst),
    .ledmatrix(M_cycle_ledmatrix),
    .pinnumber(M_cycle_pinnumber)
  );
  wire [64-1:0] M_skyfall_ledmatrix;
  wire [7-1:0] M_skyfall_score;
  wire [3-1:0] M_skyfall_stages;
  reg [1-1:0] M_skyfall_button_L;
  reg [1-1:0] M_skyfall_button_R;
  reg [1-1:0] M_skyfall_button_start;
  skyfall_3 skyfall (
    .clk(clk),
    .rst(rst),
    .button_L(M_skyfall_button_L),
    .button_R(M_skyfall_button_R),
    .button_start(M_skyfall_button_start),
    .ledmatrix(M_skyfall_ledmatrix),
    .score(M_skyfall_score),
    .stages(M_skyfall_stages)
  );
  wire [1-1:0] M_button_leftbutton_new;
  wire [1-1:0] M_button_rightbutton_new;
  wire [1-1:0] M_button_resetbutton_new;
  reg [1-1:0] M_button_leftbutton;
  reg [1-1:0] M_button_rightbutton;
  reg [1-1:0] M_button_resetbutton;
  button_4 button (
    .clk(clk),
    .rst(rst),
    .leftbutton(M_button_leftbutton),
    .rightbutton(M_button_rightbutton),
    .resetbutton(M_button_resetbutton),
    .leftbutton_new(M_button_leftbutton_new),
    .rightbutton_new(M_button_rightbutton_new),
    .resetbutton_new(M_button_resetbutton_new)
  );
  wire [8-1:0] M_sevenseg_pinnumber1;
  wire [8-1:0] M_sevenseg_pinnumber2;
  wire [8-1:0] M_sevenseg_pinnumber3;
  reg [7-1:0] M_sevenseg_score;
  reg [3-1:0] M_sevenseg_stage;
  sevenseg_5 sevenseg (
    .clk(clk),
    .rst(rst),
    .score(M_sevenseg_score),
    .stage(M_sevenseg_stage),
    .pinnumber1(M_sevenseg_pinnumber1),
    .pinnumber2(M_sevenseg_pinnumber2),
    .pinnumber3(M_sevenseg_pinnumber3)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_button_leftbutton = button_L;
    M_skyfall_button_L = M_button_leftbutton_new;
    M_button_rightbutton = button_R;
    M_skyfall_button_R = M_button_rightbutton_new;
    M_button_resetbutton = button_start;
    M_skyfall_button_start = M_button_resetbutton_new;
    M_cycle_ledmatrix = M_skyfall_ledmatrix;
    pinnumber = M_cycle_pinnumber[1+23-:24];
    M_sevenseg_score = M_skyfall_score;
    segpinnumberones = M_sevenseg_pinnumber1;
    segpinnumbertens = M_sevenseg_pinnumber2;
    M_sevenseg_stage = M_skyfall_stages;
    segpinnumberstage = M_sevenseg_pinnumber3;
  end
endmodule
