/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sevenseg_5 (
    input clk,
    input rst,
    input [6:0] score,
    input [2:0] stage,
    output reg [7:0] pinnumber1,
    output reg [7:0] pinnumber2,
    output reg [7:0] pinnumber3
  );
  
  
  
  reg [3:0] M_tens_d, M_tens_q = 1'h0;
  reg [3:0] M_ones_d, M_ones_q = 1'h0;
  
  always @* begin
    M_tens_d = M_tens_q;
    M_ones_d = M_ones_q;
    
    
    case (stage)
      3'h0: begin
        pinnumber3 = 8'hc0;
      end
      3'h1: begin
        pinnumber3 = 8'hf9;
      end
      3'h2: begin
        pinnumber3 = 8'ha4;
      end
      3'h3: begin
        pinnumber3 = 8'hb0;
      end
      3'h4: begin
        pinnumber3 = 8'h99;
      end
      default: begin
        pinnumber3 = 8'hc0;
      end
    endcase
    
    case (M_ones_q)
      1'h0: begin
        pinnumber1 = 8'hc0;
      end
      1'h1: begin
        pinnumber1 = 8'hf9;
      end
      2'h2: begin
        pinnumber1 = 8'ha4;
      end
      2'h3: begin
        pinnumber1 = 8'hb0;
      end
      3'h4: begin
        pinnumber1 = 8'h99;
      end
      3'h5: begin
        pinnumber1 = 8'h92;
      end
      3'h6: begin
        pinnumber1 = 8'h82;
      end
      3'h7: begin
        pinnumber1 = 8'hf8;
      end
      4'h8: begin
        pinnumber1 = 8'hff;
      end
      4'h9: begin
        pinnumber1 = 8'h90;
      end
      default: begin
        pinnumber1 = 8'hc0;
      end
    endcase
    
    case (M_tens_q)
      1'h0: begin
        pinnumber2 = 8'hc0;
      end
      1'h1: begin
        pinnumber2 = 8'hf9;
      end
      2'h2: begin
        pinnumber2 = 8'ha4;
      end
      2'h3: begin
        pinnumber2 = 8'hb0;
      end
      3'h4: begin
        pinnumber2 = 8'h99;
      end
      3'h5: begin
        pinnumber2 = 8'h92;
      end
      3'h6: begin
        pinnumber2 = 8'h82;
      end
      3'h7: begin
        pinnumber2 = 8'hf8;
      end
      4'h8: begin
        pinnumber2 = 8'hff;
      end
      4'h9: begin
        pinnumber2 = 8'h90;
      end
      default: begin
        pinnumber2 = 8'hc0;
      end
    endcase
    if (score == 1'h0 || score == 4'ha || score == 5'h14 || score == 5'h1e || score == 6'h28 || score == 6'h32 || score == 6'h3c || score == 7'h46 || score == 7'h50 || score == 7'h5a) begin
      M_ones_d = 1'h0;
    end
    if (score == 1'h1 || score == 4'hb || score == 5'h15 || score == 5'h1f || score == 6'h29 || score == 6'h33 || score == 6'h3d || score == 7'h47 || score == 7'h51 || score == 7'h5b) begin
      M_ones_d = 1'h1;
    end
    if (score == 2'h2 || score == 4'hc || score == 5'h16 || score == 6'h20 || score == 6'h2a || score == 6'h34 || score == 6'h3e || score == 7'h48 || score == 7'h52 || score == 7'h5c) begin
      M_ones_d = 2'h2;
    end
    if (score == 2'h3 || score == 4'hd || score == 5'h17 || score == 6'h21 || score == 6'h2b || score == 6'h35 || score == 6'h3f || score == 7'h49 || score == 7'h53 || score == 7'h5d) begin
      M_ones_d = 2'h3;
    end
    if (score == 3'h4 || score == 4'he || score == 5'h18 || score == 6'h22 || score == 6'h2c || score == 6'h36 || score == 7'h40 || score == 7'h4a || score == 7'h54 || score == 7'h5e) begin
      M_ones_d = 3'h4;
    end
    if (score == 3'h5 || score == 4'hf || score == 5'h19 || score == 6'h23 || score == 6'h2d || score == 6'h37 || score == 7'h41 || score == 7'h4b || score == 7'h55 || score == 7'h5f) begin
      M_ones_d = 3'h5;
    end
    if (score == 3'h6 || score == 5'h10 || score == 5'h1a || score == 6'h24 || score == 6'h2e || score == 6'h38 || score == 7'h42 || score == 7'h4c || score == 7'h56 || score == 7'h60) begin
      M_ones_d = 3'h6;
    end
    if (score == 3'h7 || score == 5'h11 || score == 5'h1b || score == 6'h25 || score == 6'h2f || score == 6'h39 || score == 7'h43 || score == 7'h4d || score == 7'h57 || score == 7'h61) begin
      M_ones_d = 3'h7;
    end
    if (score == 4'h8 || score == 5'h12 || score == 5'h1c || score == 6'h26 || score == 6'h30 || score == 6'h3a || score == 7'h44 || score == 7'h4e || score == 7'h58 || score == 7'h62) begin
      M_ones_d = 4'h8;
    end
    if (score == 4'h9 || score == 5'h13 || score == 5'h1d || score == 6'h27 || score == 6'h31 || score == 6'h3b || score == 7'h45 || score == 7'h4f || score == 7'h59 || score == 7'h63) begin
      M_ones_d = 4'h9;
    end
    if (score < 4'ha) begin
      M_tens_d = 1'h0;
    end else begin
      if (score < 5'h14) begin
        M_tens_d = 1'h1;
      end else begin
        if (score < 5'h1e) begin
          M_tens_d = 2'h2;
        end else begin
          if (score < 6'h28) begin
            M_tens_d = 2'h3;
          end else begin
            if (score < 6'h32) begin
              M_tens_d = 3'h4;
            end else begin
              if (score < 6'h3c) begin
                M_tens_d = 3'h5;
              end else begin
                if (score < 7'h46) begin
                  M_tens_d = 3'h6;
                end else begin
                  if (score < 7'h50) begin
                    M_tens_d = 3'h7;
                  end else begin
                    if (score < 7'h5a) begin
                      M_tens_d = 4'h8;
                    end else begin
                      if (score < 7'h64) begin
                        M_tens_d = 4'h9;
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_tens_q <= 1'h0;
      M_ones_q <= 1'h0;
    end else begin
      M_tens_q <= M_tens_d;
      M_ones_q <= M_ones_d;
    end
  end
  
endmodule
