/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_add16_41 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] sum,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] xb;
  
  reg [15:0] sum1;
  
  always @* begin
    z = 1'h0;
    v = 1'h0;
    n = 1'h0;
    sum = a;
    if (alufn[0+1-:2] == 2'h2) begin
      sum = a * b;
    end else begin
      xb = b ^ {5'h10{alufn[0+0-:1]}};
      sum1 = a + xb + alufn[0+0-:1];
      sum = sum1;
      z = (sum1 == 16'h0000);
      v = (a[15+0-:1] & xb[15+0-:1] & !sum1[15+0-:1]) || (!a[15+0-:1] & !xb[15+0-:1] & sum1[15+0-:1]);
      n = sum1[15+0-:1];
    end
  end
endmodule
